import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const packagePath = join(root, 'package.json');
const lockPath = join(root, 'package-lock.json');
const buildInfoPath = join(root, 'src', 'generated', 'buildInfo.ts');

const packageJson = JSON.parse(await readFile(packagePath, 'utf8'));
const nextVersion = bumpPatchVersion(packageJson.version);
const buildTime = formatChinaStandardTime(new Date());

packageJson.version = nextVersion;
await writeJson(packagePath, packageJson);

const lockJson = JSON.parse(await readFile(lockPath, 'utf8'));
lockJson.version = nextVersion;
if (lockJson.packages?.['']) {
  lockJson.packages[''].version = nextVersion;
}
await writeJson(lockPath, lockJson);

await mkdir(dirname(buildInfoPath), { recursive: true });
await writeFile(
  buildInfoPath,
  [
    '// Generated by npm run version:bump.',
    `export const APP_VERSION = '${nextVersion}';`,
    `export const APP_VERSION_TIME = '${buildTime}';`,
    'export const APP_VERSION_LABEL = `v${APP_VERSION} · ${APP_VERSION_TIME}`;',
    '',
  ].join('\n'),
  'utf8',
);

console.log(`Frontend version bumped to v${nextVersion} · ${buildTime}`);

function bumpPatchVersion(version) {
  const match = String(version || '').match(/^(\d+)\.(\d+)\.(\d+)$/);
  if (!match) {
    throw new Error(`package.json version must be a semver string like 0.1.0, got "${version}"`);
  }
  const [, major, minor, patch] = match;
  return `${major}.${minor}.${Number(patch) + 1}`;
}

function formatChinaStandardTime(date) {
  const cstDate = new Date(date.getTime() + 8 * 60 * 60 * 1000);
  const year = cstDate.getUTCFullYear();
  const month = pad2(cstDate.getUTCMonth() + 1);
  const day = pad2(cstDate.getUTCDate());
  const hour = pad2(cstDate.getUTCHours());
  const minute = pad2(cstDate.getUTCMinutes());
  return `${year}-${month}-${day} ${hour}:${minute} CST`;
}

function pad2(value) {
  return String(value).padStart(2, '0');
}

async function writeJson(path, value) {
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}
